### ISSUE TITLE
usb2.0不支持？

### ISSUE THREAD

**Issue by thomasmimi** [xxNull-lsk/rtl8812AU#12]
装上驱动能看到wifi，就是连不上。老电脑，没有usb3.0

**Comment by xxNull-lsk** [comment]
支持的，我家里的老电脑也是2.0口。可以正常使用。你换个口试一下。最好换屁股后面的口。不要用延长线。

**Comment by thomasmimi** [comment]
我的是笔记本，支持我就放心了，回头再装装看。
