### ISSUE TITLE
Ubuntu18.04 5.3.0-45-generic can be supported or not?

### ISSUE THREAD

**Issue by zhanghm1995** [xxNull-lsk/rtl8812AU#19]
My computer is Ubuntu18.04 and the kernel version is 5.3.0, I wonder whether it's been supported or not?

Thanks

**Comment by codesport** [comment]
@zhanghming I'd recommend that you test it out and see if it works.  If it does, would be great if you can post an update.

**Comment by zhanghm1995** [comment]
@codesport Thanks for your suggestions. I has bought Tenda U12 USB wireless card (rtl8812AU chip type) and tested it in my Ubuntu 18.04 kernel 5.3.0, I found that this driver was not work in my computer. 

And [this](https://github.com/aircrack-ng/rtl8812au) driver worked for me, I don't know why.

**Comment by codesport** [comment]
@zhanghming thanks for the update and posting a link to the working driver at https://github.com/aircrack-ng/rtl8812au.  It should help others in the same predicament. 

Honestly, this repo hasn't been updated in over 3 years. So  when it comes to drivers working on the latest OS,  it's always best to use drivers that are being actively maintained.
