### ISSUE TITLE
New branch v5.2.9 at my fork of your project

### ISSUE THREAD

**Issue by smitgd** [xxNull-lsk/rtl8812AU#7]
I have added a new branch "v5.2.9" to my up to date fork of your project. My fork/branch is here:
https://github.com/smitgd/rtl8812AU/tree/v5.2.9
It is your master branch HEAD merged with code from the Realtek ftp site ftp://ftp3.realtek.com.tw/Linux/WIFI/USB 
(Username: RTL8812A Password: J2e8Fg)
If you want to include this as a new branch in your project or merge it with your master branch, let me know if there is something I need to do such as make a pull request. It builds OK and runs OK, so far, on my TP-LINK adapter, including the new led control items and with kernel 4.12,x.
This is the items changed/fixed since v5.1.5 from the release notes pdf file:
v5.2.9_22809.20170621
1. Update FW to v52.2, 
2. Update PHYDM setting
3. Support PNO
4. Fix WOW issue
5. Fix efuse issue
6. Sync channel plan document
7. Fix DFS issue
8. Support NAPI & GRO
9. Enable Power by rate
10. Fix MP power tracking issue
11. Fix potential memory out of range
12 Support CE-RED. 2G: ETSI v2.1.1 / 5G: ETSI v2.1.0

**Comment by codesport** [comment]
@smitgd did @xxNull-lsk accept your merge yet? 

We have updates to the README.md file. We successfully installed this driver  ([@xxNull-lsk v5.1.5](https://github.com/xxNull-lsk/rtl8812AU)) on a newer USB WiFi adapter using the Realtek chipset.  Additionally we successfully tested this driver on the following kernels:

* Radeon Open Compute Linux Kernel: 4.11.0-kfd-compute-rocm-rel-1.6-148
* Complete Generic Linux kernel and headers: 4.4.0.93.98

Onto which driver version do you want us to fork and perform the pull-request?

**FYI:** Older popular drivers (e.g., https://github.com/abperiasamy/rtl8812AU_8821AU_linux) break when Ubuntu updates to the 4.4.0.93.x kernels.  [@xxNull-lsk v5.1.5](https://github.com/xxNull-lsk/rtl8812AUl) is the only driver we got to work!

**Comment by xxNull-lsk** [comment]
Sorry, I'm changed my work, so a litte busy.And I @simtgd can you create a merge to me? Thank you.

**Comment by smitgd** [comment]
@codesport, Yes I had problems with the "popular" drivers too such as wifi lockup and 5GHz not working. For me, only v5.1.5 (and now v.5.2.9) from this project have worked for me reliably. Of course, very often when a new kernel released the build fails, but so far, fairly easy to fix that.
Seems like this driver should be supported by linux kernel since rtl8812au is used in a lot of wifi adapters.

**Comment by smitgd** [comment]
@xxNull-lsk, I create a pull request to merge my v5.2.9 branch to your master. This will change a lot of files and has not really been tested with kernels older than v4.12.x (although I tried to be careful porting the kernel version specific items). If you prefer not to merge to your master, you could create a new branch v5.2.9 and I will make another pull request to merge to your new v5.2.9 branch and you can reject my original pull request. Let me know if you want this. Otherwise, the pull request I have submitted is ready to merge with your master (pending one conflict).

**Comment by xxNull-lsk** [comment]
@smitgd  OK, I will do it when back home tonight.

**Comment by codesport** [comment]
@smitgd would love to learn how you're able to fix the Kernel break issue.  Here are several threads where multiple and very smart folks were stumped on this:

1. [WiFi module 8812AU not working with kernel version >= 4.4.0-28-generic](https://askubuntu.com/questions/832329/wifi-module-8812au-not-working-with-kernel-version-4-4-0-28-generic)
2. [rtl8812au-dkms have to reinstall after every kernel update](https://www.reddit.com/r/linuxquestions/comments/4s2jai/rtl8812audkms_have_to_reinstall_after_every/)
3. [AWUS036ACH Ubuntu 17.04 Drivers problem ](https://ubuntuforums.org/showthread.php?t=2361347)

Our "solution" was to do a reinstall of the driver after every kernel update. That way, the newest kernel would always be referenced by the driver code.  However this "hack" failed beginning with the 4.4.0.93.x kernels

**Comment by codesport** [comment]
@xxNull-lsk,  100% agree with your choice in making [v5.2.9 a new branch](https://github.com/xxNull-lsk/rtl8812AU/branches), while leaving the Master at v5.1.5  

We will thus apply README.md updates to v5.1.5 which is what we tested and are currently running!

**Comment by smitgd** [comment]
@codesport 
I just tried the driver on a 4.4.0-79-generic kernel and it works OK. I build with
cd ~/rtl8812AU-smitgd
sudo make -f Makefile.dkms install
This is "neon", a kde based distro that I think is actually ubuntu xenial under the hood.
I also have 4.12.13 kernel on fedora 25 built with the same command.
It usually re-builds automatically with kernel updates unless there is a compile error due to changed kernel headers. Then you have to debug it or, better, find someone who has already fixed the problem.
I haven't tried exactly kernel 4.4.0-93.x that you mention breaking. What distro uses that version?

**Comment by codesport** [comment]
Hi @smitgd 

Most likely the August update to Ubuntu 16.04.3 LTS upgrades the kernel to 4.4.0-93.x

Also, we posted this about your repo https://github.com/gordboy/rtl8812au/issues/9  It would be an interesting exercise to do a diff on both of your branches and combine them into a master 5.2.9 branch with all the best enhancements!
